#!/bin/bash

readonly scriptDir="$([ "${BASH_SOURCE[0]}" ] && dirname -- "${BASH_SOURCE[0]}" || exit 3)"
[ -d "$scriptDir" ] || { echo >&2 "ERROR: Cannot determine script directory!"; exit 3; }

testdir="${TMPDIR:-/tmp}/WriteBackupTest"
pushd "$testdir" >/dev/null
find . -print | LC_ALL=C sort | while read filespec
do
    echo "$filespec" | sed -e '/\.1999[0-9][0-9][0-9][0-9]/n' -e '/\.200[6-8][0-9][0-9][0-9][0-9]/!s+\.[12][0-9][0-9][0-9][0-9][0-9][0-9][0-9]+.XXXXXXXX+g'
    if [ -d "$filespec" ]; then
	echo '    [DIRECTORY]'
    else
	head -n 1 "$filespec" | sed 's/^/    -> /'
    fi
done
popd >/dev/null
